version: '3'
name: oracle-database
services:
  oracle:
    container_name: oracle
    image: gvenzl/oracle-xe
    environment:
      ORACLE_RANDOM_PASSWORD: true
      APP_USER: app
      APP_USER_PASSWORD: password
    ports:
      - 1521:1521
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 3000M
